services:
  postgres:
    image: postgres:16
    container_name: staj_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: staj_user
      POSTGRES_PASSWORD: staj_sifre
      POSTGRES_DB: staj_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
