"""sertlik sutunu eklendi

Revision ID: 38b92737017d
Revises: 690b619ed8e5
Create Date: 2026-07-30 14:37:07.626680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b92737017d'
down_revision: Union[str, Sequence[str], None] = '690b619ed8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slab', sa.Column('sertlik', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slab', 'sertlik')
    # ### end Alembic commands ###
