"""ilk tablolar

Revision ID: 690b619ed8e5
Revises: 
Create Date: 2026-07-30 10:12:27.556255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '690b619ed8e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slab', 'sertlik')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slab', sa.Column('sertlik', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
