"""kontrol

Revision ID: de66655159da
Revises: 38b92737017d
Create Date: 2026-08-03 13:16:10.579017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de66655159da'
down_revision: Union[str, Sequence[str], None] = '38b92737017d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slab', sa.Column('cikis_kalinlik', sa.Numeric(), nullable=False))
    op.add_column('slab', sa.Column('giris_genislik', sa.Numeric(), nullable=False))
    op.add_column('slab', sa.Column('cikis_genislik', sa.Numeric(), nullable=False))
    op.drop_column('slab', 'giris_genisligi')
    op.drop_column('slab', 'cikis_kalinligi')
    op.drop_column('slab', 'sertlik')
    op.drop_column('slab', 'cikis_genisligi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slab', sa.Column('cikis_genisligi', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('slab', sa.Column('sertlik', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('slab', sa.Column('cikis_kalinligi', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('slab', sa.Column('giris_genisligi', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('slab', 'cikis_genislik')
    op.drop_column('slab', 'giris_genislik')
    op.drop_column('slab', 'cikis_kalinlik')
    # ### end Alembic commands ###
